FROM nvidia/cuda:11.3.1-cudnn8-runtime-ubuntu20.04

RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
RUN apt-get install -y python3 python3-distutils python3-pip

RUN mkdir /project
WORKDIR /project

COPY requirements.txt /project/

RUN pip3 install --no-cache-dir -r requirements.txt

RUN apt-get -y install ffmpeg libavcodec-extra vim git

ADD . /project

ENTRYPOINT ["/bin/bash"]