# PIPELINE DEFINITION
# Name: ml-pipeline
components:
  comp-adv-model-training:
    executorLabel: exec-adv-model-training
    inputDefinitions:
      parameters:
        batch_size:
          defaultValue: 32.0
          isOptional: true
          parameterType: NUMBER_INTEGER
        bucket_name:
          defaultValue: ''
          isOptional: true
          parameterType: STRING
        epochs:
          defaultValue: 20.0
          isOptional: true
          parameterType: NUMBER_INTEGER
        location:
          defaultValue: ''
          isOptional: true
          parameterType: STRING
        model_name:
          defaultValue: resnet
          isOptional: true
          parameterType: STRING
        project:
          defaultValue: ''
          isOptional: true
          parameterType: STRING
        staging_bucket:
          defaultValue: ''
          isOptional: true
          parameterType: STRING
        wandb_key:
          defaultValue: '16'
          isOptional: true
          parameterType: STRING
  comp-data-download:
    executorLabel: exec-data-download
  comp-model-training:
    executorLabel: exec-model-training
    inputDefinitions:
      parameters:
        batch_size:
          defaultValue: 32.0
          isOptional: true
          parameterType: NUMBER_INTEGER
        bucket_name:
          defaultValue: ''
          isOptional: true
          parameterType: STRING
        epochs:
          defaultValue: 100.0
          isOptional: true
          parameterType: NUMBER_INTEGER
        location:
          defaultValue: ''
          isOptional: true
          parameterType: STRING
        model_name:
          defaultValue: resnet
          isOptional: true
          parameterType: STRING
        project:
          defaultValue: ''
          isOptional: true
          parameterType: STRING
        staging_bucket:
          defaultValue: ''
          isOptional: true
          parameterType: STRING
        wandb_key:
          defaultValue: '16'
          isOptional: true
          parameterType: STRING
deploymentSpec:
  executors:
    exec-adv-model-training:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - adv_model_training
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.3.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"'  &&\
          \  python3 -m pip install --quiet --no-warn-script-location 'google-cloud-aiplatform'\
          \ && \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef adv_model_training(\n    project: str = \"\",\n    location:\
          \ str = \"\",\n    staging_bucket: str = \"\",\n    bucket_name: str = \"\
          \",\n    epochs: int = 20,\n    batch_size: int = 32,\n    model_name: str\
          \ = \"resnet\",\n    wandb_key:str = '16',\n):\n    print(\"Adversarial\
          \ Model Training Job\")\n\n    import google.cloud.aiplatform as aip\n\n\
          \    # Initialize Vertex AI SDK for Python\n    aip.init(project=project,\
          \ location=location, staging_bucket=staging_bucket)\n\n    container_uri\
          \ = \"us-docker.pkg.dev/vertex-ai/training/tf-gpu.2-14.py310:latest\"\n\
          \    python_package_gcs_uri = f\"{staging_bucket}/pgd-at-resnet-trainer.tar.gz\"\
          \n\n    job = aip.CustomPythonPackageTrainingJob(\n        display_name=\"\
          resnet-training\",\n        python_package_gcs_uri=python_package_gcs_uri,\n\
          \        python_module_name=\"pgd-at-resnet-trainer.train_pgd_at_resnet\"\
          ,\n        container_uri=container_uri,\n        project=project,\n    )\n\
          \n    CMDARGS = [\n        f\"--epochs={epochs}\",\n        f\"--batch_size={batch_size}\"\
          ,\n        f\"--model_name={model_name}\",\n        f\"--model_bucket={bucket_name}\"\
          ,\n        f\"--wandb_key={wandb_key}\"\n    ]\n\n    MODEL_DIR = staging_bucket\n\
          \    TRAIN_COMPUTE = \"n1-highmem-8\"\n    TRAIN_GPU = \"NVIDIA_TESLA_T4\"\
          \n    TRAIN_NGPU = 1\n\n    print(python_package_gcs_uri)\n\n    # Run the\
          \ training job on Vertex AI\n    # sync=True, # If you want to wait for\
          \ the job to finish\n    job.run(\n        model_display_name=None,\n  \
          \      args=CMDARGS,\n        replica_count=1,\n        machine_type=TRAIN_COMPUTE,\n\
          \        accelerator_type=TRAIN_GPU,\n        accelerator_count=TRAIN_NGPU,\n\
          \        base_output_dir=MODEL_DIR,\n        sync=True,\n    )\n\n"
        image: python:3.10
    exec-data-download:
      container:
        image: huckels15/ap-resnet-data
    exec-model-training:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - model_training
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.3.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"'  &&\
          \  python3 -m pip install --quiet --no-warn-script-location 'google-cloud-aiplatform'\
          \ && \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef model_training(\n    project: str = \"\",\n    location: str\
          \ = \"\",\n    staging_bucket: str = \"\",\n    bucket_name: str = \"\"\
          ,\n    epochs: int = 100,\n    batch_size: int = 32,\n    model_name: str\
          \ = \"resnet\",\n    wandb_key:str = '16',\n):\n    print(\"Model Training\
          \ Job\")\n\n    import google.cloud.aiplatform as aip\n\n    # Initialize\
          \ Vertex AI SDK for Python\n    aip.init(project=project, location=location,\
          \ staging_bucket=staging_bucket)\n\n    container_uri = \"us-docker.pkg.dev/vertex-ai/training/tf-gpu.2-14.py310:latest\"\
          \n    python_package_gcs_uri = f\"{staging_bucket}/resnet-trainer.tar.gz\"\
          \n\n    job = aip.CustomPythonPackageTrainingJob(\n        display_name=\"\
          resnet-training\",\n        python_package_gcs_uri=python_package_gcs_uri,\n\
          \        python_module_name=\"resnet-trainer.train_resnet\",\n        container_uri=container_uri,\n\
          \        project=project,\n    )\n\n    CMDARGS = [\n        f\"--epochs={epochs}\"\
          ,\n        f\"--batch_size={batch_size}\",\n        f\"--model_name={model_name}\"\
          ,\n        f\"--model_bucket={bucket_name}\",\n        f\"--wandb_key={wandb_key}\"\
          \n    ]\n\n    MODEL_DIR = staging_bucket\n    TRAIN_COMPUTE = \"n1-highmem-8\"\
          \n    TRAIN_GPU = \"NVIDIA_TESLA_T4\"\n    TRAIN_NGPU = 1\n\n    print(python_package_gcs_uri)\n\
          \n    # Run the training job on Vertex AI\n    #sync=True, # If you want\
          \ to wait for the job to finish\n    job.run(\n        model_display_name=None,\n\
          \        args=CMDARGS,\n        replica_count=1,\n        machine_type=TRAIN_COMPUTE,\n\
          \        accelerator_type=TRAIN_GPU,\n        accelerator_count=TRAIN_NGPU,\n\
          \        base_output_dir=MODEL_DIR,\n        sync=True,\n    )\n\n"
        image: python:3.10
pipelineInfo:
  name: ml-pipeline
root:
  dag:
    tasks:
      adv-model-training:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-adv-model-training
        dependentTasks:
        - model-training
        inputs:
          parameters:
            bucket_name:
              runtimeValue:
                constant: pgd-at-resnet-models-ac215
            location:
              runtimeValue:
                constant: us-east1
            project:
              runtimeValue:
                constant: secret-cipher-399620
            staging_bucket:
              runtimeValue:
                constant: gs://pgd-at-resnet-trainer
            wandb_key:
              runtimeValue:
                constant: 9981fa18ce8a6989ff4b8a46c6ef129f77cee3be
        taskInfo:
          name: Adversarial Fine-Tuning
      data-download:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-data-download
        taskInfo:
          name: Data Download
      model-training:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-model-training
        dependentTasks:
        - data-download
        inputs:
          parameters:
            bucket_name:
              runtimeValue:
                constant: resnet-models-ac215
            location:
              runtimeValue:
                constant: us-east1
            project:
              runtimeValue:
                constant: secret-cipher-399620
            staging_bucket:
              runtimeValue:
                constant: gs://resnet-trainer
            wandb_key:
              runtimeValue:
                constant: 9981fa18ce8a6989ff4b8a46c6ef129f77cee3be
        taskInfo:
          name: Model Training
schemaVersion: 2.1.0
sdkVersion: kfp-2.3.0
