name: Linting

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # Run Flake8 on src directory
      - name: Run Flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      # Run Hadolint on src directory
      - name: Run Hadolint on all Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: 'src/**/*Dockerfile'  
          format: json    
          no-fail: true
          recursive: true